/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Sonuc extends javax.swing.JFrame {

      
    private Player player1;
    private Player player2;
    private Player player3;
    private Player player4;
    public Sonuc() {
        initComponents();
    }
 public Sonuc(Player player1, Player player2, Player player3, Player player4) {
        this.player1=player1;
        this.player2=player2;
        this.player3=player3;
        this.player4=player4;
        initComponents();
        jLabel14.setText(""+player1.getToplanan_altin_miktari());
        jLabel7.setText(""+player1.getToplam_adim_sayisi());
        jLabel8.setText(""+player1.getHarcanan_altin_miktari());
        jLabel9.setText(""+player1.getKasadaki_altin_miktari());
        jLabel14.setVisible(true);
        jLabel9.setVisible(true);
        jLabel8.setVisible(true);
        jLabel7.setVisible(true);
        
        jLabel18.setText(""+player2.getToplanan_altin_miktari());
        jLabel11.setText(""+player2.getToplam_adim_sayisi());
        jLabel12.setText(""+player2.getHarcanan_altin_miktari());
        jLabel13.setText(""+player2.getKasadaki_altin_miktari());
        jLabel18.setVisible(true);
        jLabel11.setVisible(true);
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        
        jLabel22.setText(""+player3.getToplanan_altin_miktari());
        jLabel15.setText(""+player3.getToplam_adim_sayisi());
        jLabel16.setText(""+player3.getHarcanan_altin_miktari());
        jLabel17.setText(""+player3.getKasadaki_altin_miktari());
        jLabel22.setVisible(true);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        
        jLabel10.setText(""+player4.getToplanan_altin_miktari());
        jLabel19.setText(""+player4.getToplam_adim_sayisi());
        jLabel20.setText(""+player4.getHarcanan_altin_miktari());
        jLabel21.setText(""+player4.getKasadaki_altin_miktari());
        jLabel10.setVisible(true);
        jLabel19.setVisible(true);
        jLabel20.setVisible(true);
        jLabel21.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(758, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Player 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 90, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Player 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Player 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 90, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Player 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Toplanılan Altın  /  Adım Sayısı   /  Harcanan Altın Miktarı  / Kasadaki Altın Sayısı");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 10, 520, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Player 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 50, 90, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Player 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 50, 90, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Player 1");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 50, 90, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("player 1");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 220, 90, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("player 1");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 110, 90, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("player 1");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 110, 90, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("player 1");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(410, 110, 90, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("player 1");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(130, 50, 90, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("player 1");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 160, 90, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("player 1");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(290, 160, 90, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("player 1");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(400, 160, 90, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("player 1");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(120, 110, 90, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("player 1");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(190, 210, 90, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("player 1");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(280, 210, 90, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("player 1");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(390, 210, 90, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("player 1");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(120, 160, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itl.cat_plain-colour-wallpaper-hd_2525672.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sonuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sonuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
